name: scarclient
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.1.0
  carousel_slider: ^4.0.0
  charts_flutter: ^0.12.0
  country_picker: ^2.0.8
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.2.0
  flutter_native_timezone: ^2.0.0
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^0.23.0+1
  fluttertoast: ^8.0.8
  font_awesome_flutter: null
  get: ^4.5.1
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_charts: ^19.3.53
  shared_preferences: ^2.0.12
  timezone: ^0.8.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1

flutter_icons:

  android: "launcher_icon"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/values/
